# plugin_utils is used by other plugins, build first
SUBDIRS = \
	plugin_utils \
	ActuallyUselessFlag \
	adminListener \
	airspawn \
	annihilationFlag \
	autoFlagReset \
	avengerFlag \
	BattleCombatStrategy \
	BombFlag \
	bountyHunter \
	bzfscron \
	bzGunGameStyle \
	CascadeFlag \
	chathistory \
	Checkpoint \
	ctfOverseer \
	customflagsample \
	customPollTypeSample \
	CustomBZDBZones \
	CustomZoneSample \
	DeathBlossomFlag \
	DemilitarizedZones \
	dimensionDoorFlag \
	doublePoint \
	fairCTF \
	fastmap \
	flagStay \
	genoonce \
	genostats \
	givePoint \
	grenadeFlag \
	gruesomeKillerFlag \
	HoldTheFlag \
	incrementPoint \
	Kamikaze \
	keepaway \
	killall \
	koth \
	logDetail \
	mapchange \
	mappedDeathZones \
	MessageZones \
	nagware \
	neutralZones \
	NoLossOnSW \
	PhantomZoneFlagOnSpawn \
	Phoenix \
	playHistoryTracker \
	PointLessSelfKills \
	rabbitTimer \
	rabidRabbit \
	recordmatch \
	regFlag \
	RemoteDetonationFlag \
	Retroreflector \
	ReverseGeno \
	riskygeno \
	RogueGenocide \
	rrTurret \
	SAMPLE_PLUGIN \
	SandybeesServerAdministration \
	ScoreRestorer \
	SeerRadar \
	serverControl \
	serverSidePlayerSample \
	ShockwaveCenterFlag \
	ShockwaveCommand \
	shockwaveDeath \
	ShootingGallery \
	skyfireFlag \
	SneakPlugin \
	spawnFacingCenter \
	SpawnSave \
	StationCollaborationPlugin \
	superBulletBackwards \
	SuperBulletBackwardsFlag \
	superLaserFlag \
	superUser \
	teamflaggeno \
	teamflagreset \
	thiefControl \
	timedctf \
	TimeLimit \
	tripleBarrelFlag \
	TronPlugin \
	uselessGeno \
	UselessMine \
	uselessRampage \
	verticalVelocityFlag \
	WhackyWeapons \
	WingsFlagOnSpawn \
	wwzones \
	@CUSTOM_PLUGIN_LIST@

DIST_SUBDIRS = \
	$(SUBDIRS)

EXTRA_DIST = \
	api_notes \
	pushstats \
	newplug.sh

MAINTAINERCLEANFILES =	\
	Makefile.in
