# plugin_utils is used by other plugins, build first
SUBDIRS = \
	plugin_utils \
	ActuallyUselessFlag \
	airspawn \
	autoFlagReset \
	avengerFlag \
	BattleCombatStrategy \
	bountyHunter \
	bzfscron \
	CascadeFlag \
	chathistory \
	ctfOverseer \
	CustomBZDBZones \
	customflagsample \
	customPollTypeSample \
	CustomZoneSample \
	DeathBlossomFlag \
	DemilitarizedZones \
	doublePoint \
	fairCTF \
	fastmap \
	flagStay \
	genoonce \
	givePoint \
	gruesomeKillerFlag \
	HoldTheFlag \
	incrementPoint \
	keepaway \
	killall \
	koth \
	logDetail \
	mapchange \
	mappedDeathZones \
	MessageZones \
	nagware \
	neutralZones \
	Phoenix \
	playHistoryTracker \
	PointLessSelfKills \
	rabbitTimer \
	rabidRabbit \
	recordmatch \
	regFlag \
	RemoteDetonationFlag \
	Retroreflector \
	riskygeno \
	RogueGenocide \
	SAMPLE_PLUGIN \
	SandybeesServerAdministration \
	ScoreRestorer \
	SeerRadar \
	serverControl \
	serverSidePlayerSample \
	ShockwaveCenterFlag \
	shockwaveDeath \
	ShootingGallery \
	spawnAtBase \
	spawnFacingCenter \
	StationCollaborationPlugin \
	SuperBulletBackwardsFlag \
	superUser \
	teamflaggeno \
	teamflagreset \
	thiefControl \
	timedctf \
	TimeLimit \
	tripleBarrelFlag \
	TronPlugin \
	UselessMine \
	WhackyWeapons \
	WingsFlagOnSpawn \
	wwzones \
	@CUSTOM_PLUGIN_LIST@

DIST_SUBDIRS = \
	$(SUBDIRS)

EXTRA_DIST = \
	api_notes \
	pushstats \
	newplug.sh

MAINTAINERCLEANFILES =	\
	Makefile.in
