# plugin_utils is used by other plugins, build first
SUBDIRS = \
	plugin_utils \
	ActuallyUselessFlag \
	autoFlagReset \
	avengerFlag \
	BattleCombatStrategy \
	bountyHunter \
	CascadeFlag \
	ctfOverseer \
	CustomBZDBZones \
	DeathBlossomFlag \
	DemilitarizedZones \
	doublePoint \
	genoonce \
	givePoint \
	gruesomeKillerFlag \
	incrementPoint \
	koth \
	logDetail \
	mapchange \
	mappedDeathZones \
	MessageZones \
	neutralZones \
	playHistoryTracker \
	PointLessSelfKills \
	RemoteDetonationFlag \
	Retroreflector \
	riskygeno \
	RogueGenocide \
	SandybeesServerAdministration \
	ScoreRestorer \
	SeerRadar \
	ShockwaveCenterFlag \
	ShootingGallery \
	spawnAtBase \
	spawnFacingCenter \
	StationCollaborationPlugin \
	SuperBulletBackwardsFlag \
	superUser \
	teamflaggeno \
	teamflagreset \
	tripleBarrelFlag \
	TronPlugin \
	UselessMine \
	WhackyWeapons \
	WingsFlagOnSpawn \
	@CUSTOM_PLUGIN_LIST@

DIST_SUBDIRS = \
	$(SUBDIRS)

EXTRA_DIST = \
	api_notes \
	pushstats \
	newplug.sh

MAINTAINERCLEANFILES =	\
	Makefile.in
