lib_LTLIBRARIES = teamflaggeno.la

teamflaggeno_la_SOURCES = teamflaggeno.cpp
teamflaggeno_la_CPPFLAGS = -I$(top_srcdir)/include
teamflaggeno_la_LDFLAGS = -module -avoid-version -shared

AM_CPPFLAGS = $(CONF_CPPFLAGS)
AM_CFLAGS = $(CONF_CFLAGS)
AM_CXXFLAGS = $(CONF_CXXFLAGS)

MAINTAINERCLEANFILES =	\
	Makefile.in
